version: "3.5"

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: .
    restart: always
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db-server
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=66778899
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Smartshopping.pfx
    volumes:
      - ~/https-key:/https:ro
    networks:
      - localdev
  
  db-server:
    image: mysql
    container_name: db-server
    environment:
      MYSQL_ROOT_PASSWORD: "66778899"
      MYSQL_DATABASE: "DbSmartShopping"
    ports:
      - "13306:3306"
    security_opt:
      - seccomp:unconfined
    networks:
      - localdev
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "16379:6379"
    networks:
      - localdev
  